algoritmo "semnome"
// Função : 4. Faça um algoritmo que pergunte ao usuário dois números e imprima seu produto.
// Autor : Henrique Borges de Almeida Filho
// Data : 13/03/2018
// Seção de Declarações
var
   num1, num2, produto : inteiro
inicio
// Seção de Comandos
   escreva("Informe dois números. O primeiro é ")
   leia(num1)
   escreva("e o segundo é ")
   leia(num2)
   produto <- num1 * num2
   escreva("O produto entre",num1," e",num2, " é",produto)
fimalgoritmo
