algoritmo "semnome"
// Função : 1. Escreva um programa que verifique se o usuário é maior de idade
// ou não, informando.
// Autor : Henrique Borges de Almeida Filho
// Data : 13/03/2018
// Seção de Declarações
var
idade : inteiro
inicio
// Seção de Comandos
escreval("Insira sua idade: ")
leia(idade)

se(idade>=18) entao
   escreval("Você é maior de idade.")
senao
   escreval("Você é menor de idade.")
fimse
fimalgoritmo
