algoritmo "semnome"
// Função :
// Autor :
// Data : 24/03/2018
// Seção de Declarações 
var

inicio
//Escreva um programa que receba o valor de um produto e o pais de origem e retorna o valor final após a
//incidência das taxas de importação. Produtos importados dos EUA têm taxas de 5%, da França 3% e do
//Paraguai são livres de taxas. Os demais países não têm permissão para entrar no Brasil.
fimalgoritmo
