algoritmo "semnome"
// Função : 10. Escreva um programa que receba um número e retorna se ele é
// triangular. (UM NÚMERO É TRIANGULAR QUANDO É RESULTADO DO PRODUTO DE 3 NÚMEROS
// CONSECUTIVOS. EXEMPLO: 24 = 2 * 3 * 4)
// Autor : Henrique Borges de Almeida Filho
// Data : 27/03/2018
// Seção de Declarações 
var
numero,contador : real
inicio
escreval("Insira um número: ")
leia(numero)
contardor <- 2

fimalgoritmo
