algoritmo "semnome"
// Função : 8. Leia um número n e imprima sua tabuada (de 0 a 9).
// Autor : Henrique Borges de Almeida Filho
// Data : 31/03/2018
var
num : real
contador,contadorIntervalo : inteiro
inicio
escreval("Insira um número")
   leia(num)
para contador de 1 ate 10 passo 1 faca
   se(num>=30) e (num<=90) entao
      contadorIntervalo <- contadorIntervalo + 1
   fimse
   contador <- contador + 1
fimpara
escreval(contadorIntervalo," números estão entre 30 e 90.")
fimalgoritmo
