algoritmo "semnome"
// Função : 5. Faça um algoritmo que pergunte o nome e idade do usuário e imprima “Olá, <nome da pessoa>, você tem <idade da pessoa> anos”.
// Autor : Henrique Borges de Almeida Filho
// Data : 13/03/2018
// Seção de Declarações
var
   nome : caracter
   idade : inteiro
inicio
// Seção de Comandos
   escreva("Informe seu nome: ")
   leia(nome)
   escreva("Informe sua idade: ")
   leia(idade)
   escreva("Olá ",nome,", você tem",idade, " anos.")
fimalgoritmo
