algoritmo "semnome"
// Função : 8. Faça um algoritmo que solicita o raio de uma circunferência e exibe seu perímetro e área.
// Autor : Henrique Borges de Almeida Filho
// Data : 13/03/2018
// Seção de Declarações
var
   raio, perimetro, area : real
inicio
// Seção de Comandos
   escreva("Informe o raio da circunferência: ")
   leia(raio)
   perimetro <- 2 * 3.14 * raio
   area <- 3.14 * raio * raio
   escreva("O perímetro da circunferência é",perimetro," e a área é",area)
fimalgoritmo
