algoritmo "semnome"
// Função :
// Autor :
// Data : 13/03/2018
// Seção de Declarações
var
num1,num2 : inteiro
inicio
// Seção de Comandos
escreval("Insira o primeiro número: ")
leia(num1)
escreval("Insira o segundo número: ")
leia(num2)

se(num1=num2)entao
escreval("Os números são iguais.")
fimse

se(num1>num2)entao
   escreval(num1," é maior que ",num2)
fimse
se(num2<num1)entao
   escreval(num2," é maior que ",num1)
fimse

fimalgoritmo
