algoritmo "semnome"
// Função :
// Autor :
// Data : 15/03/2018
// Seção de Declarações 
var
código : real
inicio
//O cardápio de uma lanchonete é o seguinte:
//Especificação Preço unitário
//100 Cachorro quente 1,10
//101 Bauru simples 1,30
//102 Bauru c/ovo 1,50
//103 Hamburger 1,10
//104 Cheeseburger 1,30
//105 Refrigerante 1,00
//Escreva um programa que receba o código do item pedido, a quantidade desejada e informe o valor final.

fimalgoritmo
