algoritmo "semnome"
// Função : 6. Faça um programa que imprima na tela apenas os números ímpares múltiplos de três entre 1 e 50.
// Autor : Henrique Borges de Almeida Filho
// Data : 24/04/2018
var
cont : inteiro
resultado : real
inicio
para cont de 50 ate 1 passo -1 faca
   resultado <- cont/3
   se(resultado=int(resultado))entao
      se(cont%2<>0)entao
         escreval(cont)
      fimse
   fimse
fimpara
fimalgoritmo
